name = "cordoba"
uuid = "e2452cbb-75db-4735-b721-a4abbc529286"
authors = ["Su-"]
version = "0.1.0"

[compat]
julia = "1.5.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
